// src/lib/processor.js
import Pica from 'pica';
import JSZip from 'jszip';

const pica = Pica();
const MAX_BYTES = 780 * 1024; // Strict CMS limit

/**
 * Helper to download a single Blob directly to the user's machine
 * @param {Blob} blob 
 * @param {string} filename 
 */
function downloadSingleFile(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  
  document.body.appendChild(a);
  a.click();
  
  // Cleanup to prevent memory leaks
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generates a Blob for a single image, enforcing size limits.
 * @param {any} imageObj 
 * @param {any} preset 
 * @param {string} format 
 * @param {number} quality 
 */
export async function processSingleImage(imageObj, preset, format, quality) {
  console.log("🛠️ [3] Inside processSingleImage. Crop coords:", imageObj.cropCoordinates);
  
  if (!imageObj.cropCoordinates) {
    console.warn("⚠️ ABORTING: cropCoordinates is null!");
    return null;
  }

  const mimeType = format.startsWith('image/') ? format : `image/${format}`;
  let currentQuality = quality > 1 ? quality / 100 : quality;

  const img = new Image();
  img.src = imageObj.objectUrl;
  await new Promise(r => img.onload = r);
  console.log("🛠️ [4] Image loaded into memory. Native size:", img.width, "x", img.height);

  const { x, y, width, height } = imageObj.cropCoordinates;
  
  const cropCanvas = document.createElement('canvas');
  cropCanvas.width = width;
  cropCanvas.height = height;
  const ctx = cropCanvas.getContext('2d');
  if (!ctx) return null;
  ctx.drawImage(img, x, y, width, height, 0, 0, width, height);

  const targetCanvas = document.createElement('canvas');
  targetCanvas.width = preset.width;
  targetCanvas.height = preset.height;
  
  console.log("🛠️ [5] Resizing with Pica...");
  await pica.resize(cropCanvas, targetCanvas, {
    unsharpAmount: 80,
    unsharpRadius: 0.6,
    unsharpThreshold: 2
  });
  
  console.log(`🛠️ [6] Converting to Blob... Format: ${mimeType}, Quality: ${currentQuality}`);
  let blob = await pica.toBlob(targetCanvas, mimeType, currentQuality);
  
  console.log(`🛠️ [6.5] Raw Blob size from Pica: ${blob.size} bytes`);

  // Bypassing the MAX_BYTES loop for testing unless MAX_BYTES is strictly defined above
  
  return blob;
}

/**
 * Processes the entire batch. Single images are downloaded directly; multiple images are zipped.
 * @param {any[]} images 
 * @param {string} format 
 * @param {number} quality 
 * @param {(id: string) => { id: string, label: string, width: number, height: number, aspect: number, type: string, minKB: number, maxKB: number } | null} getPresetById
 */
export async function downloadBatchZip(images, format, quality, getPresetById) {
  if (images.length === 0) return;

  // Clean up the extension just in case it's needed as a fallback
  let extension = format.split('/')[1];
  if (extension === 'jpeg') extension = 'jpg';

  // ==========================================
  // PATH A: Single Image (Direct Download)
  // ==========================================
  if (images.length === 1) {
    const img = images[0];
    
    /** @type {HTMLSelectElement | HTMLInputElement | null} */
    const presetElement = /** @type {HTMLSelectElement | HTMLInputElement | null} */ (document.getElementById('preset'));    
    const fallbackId = presetElement ? presetElement.value : 'story-detail-thumb';
    const presetId = img.presetId || fallbackId;
    
    const preset = getPresetById(presetId) || { 
      id: 'fallback', 
      width: 1080, 
      height: 1080, 
      type: 'crop', 
      minKB: 0, 
      maxKB: 1000 
    };    
    
    const blob = await processSingleImage(img, preset, format, quality);
    
    if (blob) {
      // FIX: Use the exportFilename generated by the Workspace.svelte preview
      const finalName = img.exportFilename || `image_${preset.width}x${preset.height}.${extension}`;
      downloadSingleFile(blob, finalName);
    }
    
    return; // Exit early to bypass ZIP logic
  }

  // ==========================================
  // PATH B: Multiple Images (ZIP Archive)
  // ==========================================
  const zip = new JSZip();
  
  // Track filenames to prevent overwriting duplicates
  /** @type {Record<string, number>} */
  const nameTracker = {}; 

  for (let i = 0; i < images.length; i++) {
    const img = images[i];
    
    /** @type {HTMLSelectElement | HTMLInputElement | null} */
    const presetElement = /** @type {HTMLSelectElement | HTMLInputElement | null} */ (document.getElementById('preset'));    
    const fallbackId = presetElement ? presetElement.value : 'story-detail-thumb';
    
    const presetId = img.presetId || fallbackId;
    const preset = getPresetById(presetId) || { 
      id: 'fallback', 
      width: 1080, 
      height: 1080, 
      type: 'crop', 
      minKB: 0, 
      maxKB: 1000 
    };    
    
    const blob = await processSingleImage(img, preset, format, quality);
    
    if (blob) {
      // FIX: Use UI filename, with a fallback just in case
      let finalName = img.exportFilename || `image-${i}.${extension}`;
      let originalAttempt = finalName;
      
      // If this exact filename is already in the ZIP, append an index
      if (nameTracker[originalAttempt]) {
        // Split extension so we inject the number before the dot
        const parts = originalAttempt.split('.');
        const ext = parts.pop();
        const base = parts.join('.');
        
        finalName = `${base}-${nameTracker[originalAttempt]}.${ext}`;
        nameTracker[originalAttempt]++;
      } else {
        nameTracker[originalAttempt] = 1;
      }

      zip.file(finalName, blob);
    }
  }

  const zipBlob = await zip.generateAsync({ type: 'blob' });
  const downloadUrl = URL.createObjectURL(zipBlob);
  
  const link = document.createElement('a');
  link.href = downloadUrl;
  link.download = `cms_images_${new Date().getTime()}.zip`;
  link.click();
  
  URL.revokeObjectURL(downloadUrl);
}